In [1]:
import numpy as np

In [25]:
X = np.array([[147, 150, 153, 158, 163, 165, 168, 170, 173, 175, 178, 180, 183]]).T
y = np.array([[ 49, 50, 51,  54, 58, 59, 60, 62, 63, 64, 66, 67, 68]]).T

In [27]:
X.shape

(13, 1)

In [42]:
one = np.ones((X.shape[0], 1))

In [43]:
one

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [59]:
Xbar = np.concatenate((one, X), axis = 1)

In [60]:
Xbar

array([[  1., 147.],
       [  1., 150.],
       [  1., 153.],
       [  1., 158.],
       [  1., 163.],
       [  1., 165.],
       [  1., 168.],
       [  1., 170.],
       [  1., 173.],
       [  1., 175.],
       [  1., 178.],
       [  1., 180.],
       [  1., 183.]])

In [61]:
A = np.dot(Xbar.T, Xbar)

In [62]:
A

array([[1.30000e+01, 2.16300e+03],
       [2.16300e+03, 3.61527e+05]])

In [65]:
b = np.dot(Xbar.T, y)

In [66]:
b

array([[   771.],
       [129198.]])

In [67]:
w = np.dot(np.linalg.pinv(A), b)

In [68]:
w

array([[-33.73541021],
       [  0.55920496]])

In [71]:
w_0 = w[0][0]

In [73]:
w_1 = w[1][0]

In [76]:
x0 = np.linspace(145, 185, 2)

In [77]:
x0

array([145., 185.])

In [78]:
y0 = w_0 + w_1 * x0

In [79]:
y0

array([47.34930928, 69.71750775])